# This gh-action will build and publish the electron app to the GH releases page
name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: electronuserland/builder:wine
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NODE_ENV: production
        VITE_API_URL: ${{ vars.VITE_API_URL }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./package-lock.json, svelte/package-lock.json
      - name: Publish
        run: |
          pwd
          ls
          npm ci
          ls node_modules
          cd svelte
          pwd
          ls
          npm ci
          ls node_modules
          cd ..
          npm run publish
