# This gh-action will build and publish the electron app to the GH releases page
name: Publish

on:
  push:
    branches:
      - main
    paths:
      - 'electron/**'
      - 'svelte/src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: electronuserland/builder:wine
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VITE_API_URL: ${{ vars.VITE_API_URL }}


    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: |
          mkdir /github/home/.wine
          export WINEPREFIX=/github/home/.wine
          ls -la /github/home
          npm run setup
          npm run publish

      - name: Configure git
        run: |
          git config --global user.email "<>"
          git config --global user.name "Quantum Assembler"
          git config --global --add safe.directory "$(pwd)"
      - name: Update version
        # Don't tag the commit, it will be tagged by Publish step
        # Make the commit message "[ci skip] Bump version to vX.X.X"
        run: |
          npm config set git-tag-version false
          export VERSION=$(npm version patch)
          git add .
          git commit -m "[ci skip] Bump version to $VERSION"
          git push
