# This gh-action will build and publish the electron app to the GH releases page
name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: electronuserland/builder:wine
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        VITE_API_URL: ${{ vars.VITE_API_URL }}

    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: |
          npm run setup
          export NODE_ENV=production
          npm run publish
